import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import { ConvexClientProvider } from "@/context/convex";
import { Header } from "@/components/header";
import { Separator } from "@/components/ui/separator";
import {
  BookmarkIcon,
  CalendarIcon,
  ClockIcon,
  HomeIcon,
} from "@radix-ui/react-icons";
import { Sidenav, SidenavItem } from "@/components/sidenav";
import { ThemeProvider } from "@/context/theme";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const sidenavItems: SidenavItem[] = [
  {
    href: "/",
    icon: <CalendarIcon />,
    label: "My events",
  },
  {
    href: "/list?past=true",
    icon: <ClockIcon />,
    label: "Past events",
  },
  {
    href: "/venues",
    icon: <HomeIcon />,
    label: "Venues",
  },
];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <ConvexClientProvider>
        <html lang="en">
          <body className={inter.className}>
            <ThemeProvider attribute="class" defaultTheme="light" enableSystem>
              <div className="flex min-h-screen flex-col">
                <Header />

                <div className="flex flex-1 flex-row gap-24 px-24 py-12">
                  <Sidenav items={sidenavItems} />

                  {children}
                </div>
              </div>
            </ThemeProvider>
          </body>
        </html>
      </ConvexClientProvider>
    </ClerkProvider>
  );
}
